#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Sat Mar 16 00:21:56 IST 2019
apiSecret=2ba4c3f4588ea0e8579950db9fed48e87bffa4972e763cf48a425eb74dd76f63
